sudo: required
services:
    docker
before_install:
    - docker build -t sureka28/singlecontainer -f Dockerfile.dev .
script:
    - docker run -e CI=true sureka28/singlecontainer npm run test -- --coverage
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "single-container"
    env: "SingleContainer-env"
    bucket_name: "elasticbeanstalk-us-east-2-674706550247"
    bucket_path: "single-container"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    